#
[versions]
kotlin-base = "2.0.20"
ksp = "2.0.20-1.0.25"

google-auto-service = "1.1.1"

kotlinpoet = "1.18.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-base" }
# kotlin reflection
kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-base" }


kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlin-ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }


google-auto-service = { module = "com.google.auto.service:auto-service", version.ref = "google-auto-service" }



[plugins]
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-base" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-base" }